Repository orbitdb/orbit-db, pull requests merged in 2018-08, with the labels that each got.

#422 docs: Add note about community calls
  README.md
Labels: In Progress

#421 docs(README.md): Add Haja and Maintainer sponsors
  README.md
Labels: In Progress, docs

#404 Adding auto-generated CircleCI 2.0 config file
  .circleci/config.yml
Labels: In Progress

#424 Remove CircleCI 1.0 config file
  circle.yml
Labels: In Progress

#428 docs: Add TOCs using an npm script
  API.md
  CHANGELOG.md
  GUIDE.md
  README.md
  package-lock.json
  package.json
Labels: In Progress, docs, enhancement
